In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Everything works!")

Everything works!

In [6]:
# loading the dataset 
import pandas as pd

df = pd.read_csv("../data/raw/hies_state.csv")

df.head()

,date,state,income_mean,income_median,expenditure_mean,gini,poverty
0,2022-01-01,Johor,8517,6879,5342,0.366,4.6
1,2024-01-01,Johor,9484,7712,5927,0.348,2.5
2,2022-01-01,Kedah,5550,4402,3765,0.359,9.0
3,2024-01-01,Kedah,5793,4895,4028,0.334,8.4
4,2022-01-01,Kelantan,4885,3614,3505,0.385,13.2

In [7]:
#check the dataset 
df.shape

(32, 7)

In [8]:
df.columns

Index(['date', 'state', 'income_mean', 'income_median', 'expenditure_mean',
       'gini', 'poverty'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              32 non-null     str
 1   state             32 non-null     str
 2   income_mean       32 non-null     int64
 3   income_median     32 non-null     int64
 4   expenditure_mean  32 non-null     int64
 5   gini              32 non-null     float64
 6   poverty           32 non-null     float64
dtypes: float64(2), int64(3), str(2)
memory usage: 1.9 KB

In [10]:
df.describe()

       income_mean  income_median  expenditure_mean       gini    poverty
count     32.00000      32.000000         32.000000  32.000000  32.000000
mean    8159.84375    6477.312500       5178.031250   0.347219   5.659375
std     2807.80007    2190.557028       1614.152199   0.031671   4.800730
min     4885.00000    3614.000000       3342.000000   0.263000   0.100000
25%     6048.50000    4855.750000       3999.750000   0.326750   2.000000
50%     7276.50000    5734.500000       4587.500000   0.352000   4.300000
75%     8802.50000    7383.750000       5869.250000   0.369250   7.725000
max    13985.00000   10802.000000       9186.000000   0.405000  19.700000

In [11]:
df.isnull().sum()

date                0
state               0
income_mean         0
income_median       0
expenditure_mean    0
gini                0
poverty             0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
#check the date and state checks 
df['date'].unique()

<StringArray>
['2022-01-01', '2024-01-01']
Length: 2, dtype: str

In [14]:
df['state'].unique()

<StringArray>
[            'Johor',             'Kedah',          'Kelantan',
            'Melaka',   'Negeri Sembilan',            'Pahang',
      'Pulau Pinang',             'Perak',            'Perlis',
          'Selangor',        'Terengganu',             'Sabah',
           'Sarawak', 'W.P. Kuala Lumpur',       'W.P. Labuan',
    'W.P. Putrajaya']
Length: 16, dtype: str

In [15]:
#clean the date column 
df['date'] = pd.to_datetime(df['date'])

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              32 non-null     datetime64[us]
 1   state             32 non-null     str
 2   income_mean       32 non-null     int64
 3   income_median     32 non-null     int64
 4   expenditure_mean  32 non-null     int64
 5   gini              32 non-null     float64
 6   poverty           32 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(3), str(1)
memory usage: 1.9 KB

In [17]:
df['year'] = df['date'].dt.year

In [18]:
df[['date', 'year', 'state']].head()

        date  year     state
0 2022-01-01  2022     Johor
1 2024-01-01  2024     Johor
2 2022-01-01  2022     Kedah
3 2024-01-01  2024     Kedah
4 2022-01-01  2022  Kelantan

In [19]:
df.groupby('year')['state'].count()

year
2022    16
2024    16
Name: state, dtype: int64

In [20]:
# saved the cleaned dataset 
df.to_csv("../data/processed/hies_state_clean.csv", index=False)

In [22]:
#load district-level datasets 

income = pd.read_csv("../data/raw/hh_income_district.csv")
poverty = pd.read_csv("../data/raw/hh_poverty_district.csv")
inequality = pd.read_csv("../data/raw/hh_inequality_district.csv")

In [23]:
income = pd.read_csv("../data/raw/hh_income_district.csv")
poverty = pd.read_csv("../data/raw/hh_poverty_district.csv")
inequality = pd.read_csv("../data/raw/hh_inequality_district.csv")

print("Income:", income.shape)
print("Poverty:", poverty.shape)
print("Inequality:", inequality.shape)

Income: (480, 5)
Poverty: (480, 5)
Inequality: (480, 4)

In [24]:
print("INCOME")
display(income.head())

print("POVERTY")
display(poverty.head())

print("INEQUALITY")
display(inequality.head())

INCOME

   state     district        date  income_mean  income_median
0  Johor   Batu Pahat  2019-01-01         7392           6504
1  Johor   Batu Pahat  2022-01-01         7419           6347
2  Johor   Batu Pahat  2024-01-01         9006           7555
3  Johor  Johor Bahru  2019-01-01         9315           7342
4  Johor  Johor Bahru  2022-01-01         9869           8232

POVERTY

   state     district        date  poverty_absolute  poverty_relative
0  Johor   Batu Pahat  2019-01-01               2.9               9.0
1  Johor   Batu Pahat  2022-01-01               5.1              19.4
2  Johor   Batu Pahat  2024-01-01               2.4              11.6
3  Johor  Johor Bahru  2019-01-01               3.3              12.8
4  Johor  Johor Bahru  2022-01-01               3.7              10.4

INEQUALITY

   state     district        date   gini
0  Johor   Batu Pahat  2019-01-01  0.295
1  Johor   Batu Pahat  2022-01-01  0.338
2  Johor   Batu Pahat  2024-01-01  0.316
3  Johor  Johor Bahru  2019-01-01  0.388
4  Johor  Johor Bahru  2022-01-01  0.359

In [25]:
print("Income columns:", income.columns.tolist())
print("Poverty columns:", poverty.columns.tolist())
print("Inequality columns:", inequality.columns.tolist())

Income columns: ['state', 'district', 'date', 'income_mean', 'income_median']
Poverty columns: ['state', 'district', 'date', 'poverty_absolute', 'poverty_relative']
Inequality columns: ['state', 'district', 'date', 'gini']

In [26]:
print("Income years:")
print(income["date"].unique())

print("\nPoverty years:")
print(poverty["date"].unique())

print("\nInequality years:")
print(inequality["date"].unique())

Income years:
<StringArray>
['2019-01-01', '2022-01-01', '2024-01-01']
Length: 3, dtype: str

Poverty years:
<StringArray>
['2019-01-01', '2022-01-01', '2024-01-01']
Length: 3, dtype: str

Inequality years:
<StringArray>
['2019-01-01', '2022-01-01', '2024-01-01']
Length: 3, dtype: str

In [27]:
#MERGE THE DATASETS 
income_df = income.copy()
poverty_df = poverty.copy()
inequality_df = inequality.copy()

# Convert dates to datetime
income_df["date"] = pd.to_datetime(income_df["date"])
poverty_df["date"] = pd.to_datetime(poverty_df["date"])
inequality_df["date"] = pd.to_datetime(inequality_df["date"])

# Merge income + poverty
merged_df = pd.merge(
    income_df,
    poverty_df,
    on=["state", "district", "date"],
    how="inner"
)

# Merge with inequality
merged_df = pd.merge(
    merged_df,
    inequality_df,
    on=["state", "district", "date"],
    how="inner"
)

print("Merged dataset shape:", merged_df.shape)
display(merged_df.head())

Merged dataset shape: (480, 8)

,state,district,date,income_mean,income_median,poverty_absolute,poverty_relative,gini
0,Johor,Batu Pahat,2019-01-01,7392,6504,2.9,9.0,0.295
1,Johor,Batu Pahat,2022-01-01,7419,6347,5.1,19.4,0.338
2,Johor,Batu Pahat,2024-01-01,9006,7555,2.4,11.6,0.316
3,Johor,Johor Bahru,2019-01-01,9315,7342,3.3,12.8,0.388
4,Johor,Johor Bahru,2022-01-01,9869,8232,3.7,10.4,0.359

In [28]:
print("Missing values:")
print(merged_df.isnull().sum())

print("\nDuplicate rows:")
print(merged_df.duplicated().sum())

Missing values:
state               0
district            0
date                0
income_mean         0
income_median       0
poverty_absolute    0
poverty_relative    0
gini                0
dtype: int64

Duplicate rows:
0

In [29]:
print("\nYears:")
print(sorted(merged_df["date"].dt.year.unique()))

print("\nNumber of districts:")
print(merged_df["district"].nunique())

Years:
[np.int32(2019), np.int32(2022), np.int32(2024)]

Number of districts:
172

In [30]:
merged_df.to_csv(
    "../data/processed/finsight_merged.csv",
    index=False
)

print("Merged dataset saved successfully!")

Merged dataset saved successfully!

In [31]:
#CREATE A FUTURE FINANCIAL RISK TARGET 
# Sort by district and year
merged_df = merged_df.sort_values(["district", "date"])

# Calculate change in relative poverty for each district
merged_df["future_poverty"] = merged_df.groupby("district")["poverty_relative"].shift(-1)

merged_df["poverty_change"] = (
    merged_df["future_poverty"] - merged_df["poverty_relative"]
)

display(
    merged_df[
        ["state", "district", "date", "poverty_relative",
         "future_poverty", "poverty_change"]
    ].head(15)
)

,state,district,date,poverty_relative,future_poverty,poverty_change
99,Melaka,Alor Gajah,2019-01-01,18.8,14.1,-4.7
100,Melaka,Alor Gajah,2022-01-01,14.1,11.4,-2.7
101,Melaka,Alor Gajah,2024-01-01,11.4,NaN,NaN
298,Sarawak,Asajaya,2019-01-01,28.4,19.9,-8.5
299,Sarawak,Asajaya,2022-01-01,19.9,26.2,6.3
300,Sarawak,Asajaya,2024-01-01,26.2,NaN,NaN
66,Kelantan,Bachok,2019-01-01,10.7,10.4,-0.3
67,Kelantan,Bachok,2022-01-01,10.4,12.1,1.7
68,Kelantan,Bachok,2024-01-01,12.1,NaN,NaN
162,Perak,Bagan Datuk,2019-01-01,11.0,19.8,8.8
163,Perak,Bagan Datuk,2022-01-01,19.8,18.6,-1.2
164,Perak,Bagan Datuk,2024-01-01,18.6,NaN,NaN
30,Kedah,Baling,2019-01-01,23.9,19.7,-4.2
31,Kedah,Baling,2022-01-01,19.7,24.0,4.3
32,Kedah,Baling,2024-01-01,24.0,NaN,NaN

In [32]:
print(merged_df["poverty_change"].describe())

count    308.000000
mean      -0.163961
std        6.840155
min      -37.100000
25%       -3.825000
50%       -0.100000
75%        2.925000
max       32.700000
Name: poverty_change, dtype: float64

In [33]:
#CHECK THE RISK CLASSES 
risk_df = merged_df.dropna(subset=["poverty_change"]).copy()

risk_df["financial_risk"] = pd.cut(
    risk_df["poverty_change"],
    bins=[-float("inf"), 0, 3, float("inf")],
    labels=["Low", "Medium", "High"],
    right=False
)

print("Risk distribution:")
print(risk_df["financial_risk"].value_counts())

Risk distribution:
financial_risk
Low       154
Medium     77
High       77
Name: count, dtype: int64

In [34]:
print("\nRisk percentage:")
print(
    risk_df["financial_risk"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Risk percentage:
financial_risk
Low       50.0
Medium    25.0
High      25.0
Name: proportion, dtype: float64

In [35]:
# Create final ML dataset
ml_df = risk_df.copy()

# Create numeric target
ml_df["financial_risk"] = ml_df["financial_risk"].map({
    "Low": 0,
    "Medium": 1,
    "High": 2
})

# Select features and target
ml_df = ml_df[
    [
        "state",
        "district",
        "date",
        "income_mean",
        "income_median",
        "poverty_absolute",
        "poverty_relative",
        "gini",
        "financial_risk"
    ]
]

print("ML dataset shape:", ml_df.shape)
display(ml_df.head())

ML dataset shape: (308, 9)

,state,district,date,income_mean,income_median,poverty_absolute,poverty_relative,gini,financial_risk
99,Melaka,Alor Gajah,2019-01-01,7050,5907,3.8,18.8,0.356,0
100,Melaka,Alor Gajah,2022-01-01,7235,5611,4.8,14.1,0.343,0
298,Sarawak,Asajaya,2019-01-01,4316,3101,20.0,28.4,0.383,0
299,Sarawak,Asajaya,2022-01-01,4557,3929,17.9,19.9,0.301,2
66,Kelantan,Bachok,2019-01-01,4728,3621,13.1,10.7,0.361,0

In [36]:
print(ml_df["financial_risk"].value_counts())

financial_risk
0    154
1     77
2     77
Name: count, dtype: int64